base_url = "https://twitter.com/"

browser_name_chrome = "chrome"
browser_name_firefox = "firefox"

browser_non_supported_message = "{} browser is not supported"
browser_type_error_message = "string_browser_name must be string"
url_type_error_message = "URL must be a string"

assert_element_is_not_displayed_message = "'{}' is not displayed"
assert_element_is_not_enabled_message = "'{}' is not enabled"
assert_difference_in_titles_message = "Difference in titles. Eth: {}; Curr: {}"
assert_url_message = "Curr URL does not contain eth URL. Eth: {}; Curr: {}"
assert_html_of_element_is_not_defined_message = "html of element is not defined"
assert_element_is_not_clickable_message = "Element with locator {} is not clickable"
assert_element_with_css_selector_is_not_presence = "Element with CSS locator {} is not found in DOM"
assert_element_with_css_selector_is_presence = "Element with CSS locator {} is found in DOM"

html_tag_body = "body"
html_tag_form = "form"
html_tag_nav = "nav"
html_tag_a = "a"
html_tag_header = "header"
html_tag_main = "main"
html_tag_span = "span"

attribute_value = "value"

general_id_body = "react-root"

tag_timeout_message = "Element '{}' does not contain the '{}' tag"
name_timeout_message = "Element '{}' does not contain the '{}' name"
class_timeout_message = "Element '{}' does not contain the '{}' class"
css_selector_timeout_message = "Element '{}' does not contain the '{}' css selector"

input_enabling_assert_message = "Input is not enabled: {}"
href_enabling_assert_message = "Link is not enabled: {}"


initial_page_name_username = "session[username_or_email]"
initial_page_name_password = "session[password]"
initial_page_css_selector_timeout_message = "Element '{}' does not contain the '{}' css selector"
initial_page_data_testid_form_submit = "LoginForm_Login_Button"
initial_page_css_selector_form_submit = f"div[data-testid='{initial_page_data_testid_form_submit}']"
initial_page_data_testid_signup = "signupButton"
initial_page_css_selector_signup = f"a[data-testid='{initial_page_data_testid_signup}']"
initial_page_data_testid_login = "loginButton"
initial_page_css_selector_login = f"a[data-testid='{initial_page_data_testid_login}']"

login_page_name_username = "session[username_or_email]"
login_page_name_password = "session[password]"
login_page_data_testid_form_submit = "LoginForm_Login_Button"
login_page_css_selector_form_submit = f"div[data-testid='{login_page_data_testid_form_submit}']"
login_page_data_testid_signup = "signupButton"
login_page_css_selector_signup = f"a[data-testid='{login_page_data_testid_signup}']"
login_page_data_testid_login = "loginButton"
login_page_css_selector_login = f"a[data-testid='{login_page_data_testid_login}']"
login_page_difference_in_values_assert_message = "Difference in input's values. Eth: {}; Curr: {}"

main_page_data_testid_primary_column = "primaryColumn"
main_page_css_selector_primary_column = f"div[data-testid='{main_page_data_testid_primary_column}']"
main_page_data_testid_sidebar_column = "sidebarColumn"
main_page_css_selector_sidebar_column = f"div[data-testid='{main_page_data_testid_sidebar_column}']"
main_page_data_testid_new_tweet_btn = "SideNav_NewTweet_Button"
main_page_css_selector_new_tweet_btn = f"a[data-testid='{main_page_data_testid_new_tweet_btn}']"
main_page_data_testid_home_btn = "AppTabBar_Home_Link"
main_page_css_selector_home_btn = f"a[data-testid='{main_page_data_testid_home_btn}']"
main_page_aria_labelledby_modal_form = "modal-header"
main_page_css_selector_modal_form = f"div[aria-labelledby='{main_page_aria_labelledby_modal_form}']"
main_page_class_draft_editor = "DraftEditor-editorContainer"
main_page_class_draft_editor_content = "public-DraftEditor-content"
main_page_data_testid_modal_form_toolbar = "toolBar"
main_page_css_selector_modal_form_toolbar = f"div[data-testid='{main_page_data_testid_modal_form_toolbar}']"
main_page_data_testid_modal_form_tweet_btn = "tweetButton"
main_page_css_selector_modal_form_tweet_btn = f"div[data-testid='{main_page_data_testid_modal_form_tweet_btn}']"
main_page_difference_in_values_assert_message = "Difference in input's values. Eth: {}; Curr: {}"
main_page_data_testid_own_tweet = "tweet"
main_page_css_selector_own_tweet = f"div[data-testid='{main_page_data_testid_own_tweet}']"
main_page_own_tweet_is_nof_found = "Tweet is not found with text: {}"

class_is_not_present_timeout_message = "Element with class {} is not present"
id_is_not_present_timeout_message = "Element with ID: {} is not present in DOM"

main_page_id_body = "body"
main_page_tag_img = "img"
main_page_tag_timeout_message = "Element '{}' does not contain the '{}' tag"
main_page_id_searchform = "searchform"
main_page_class_FPdoLc = "FPdoLc"
main_page_name_btnK = "btnK"
main_page_name_btnI = "btnI"
main_page_tag_input = "input"
main_page_inputs_timeout_message = "Inputs are not present"
main_page_input_with_defined_class_is_not_found_assert_message = "Input with defined class is not found"
main_page_attribute_class = "class"
main_page_img_is_not_displayed_assert_message = "Image is not displayed"
main_page_attribute_alt = "alt"
main_page_img_assert_message = "Attribute '{}' of image. Eth: {} Curr: {}"
main_page_input_enabling_assert_message = "Input of searching is not enabled"
main_page_attribute_value = "value"
main_page_class_UUbT9 = "UUbT9"
main_page_element_with_class_is_not_visible_assert_message = "Element with class {} is not visible"
