import allure
import pytest
from datetime import datetime
from driverfactory.driverfactory import DriverFactory
from values import strings
from pageobjects.initialpage import InitialPage
from pageobjects.loginpage import LoginPage
from pageobjects.mainpage import MainPage


@pytest.fixture(scope="class")
def driver_init(request):
    defined_browser_str = request.config.getoption("--cmd_opt_browser_name")
    navigated_url = strings.base_url
    with allure.step("Setup. Launch webdriver for browser: {0}".format(defined_browser_str)):
        factory = DriverFactory()
        driver = factory.get_driver(defined_browser_str)
        request.cls.driver = driver
        with allure.step("Navigate to {}".format(navigated_url)):
            driver.navigate(navigated_url)
    yield
    with allure.step("Teardown. Close all instances of webdriver"):
        driver.instance.quit()


@pytest.mark.usefixtures("driver_init")
class TestTwitter:
    def test_initial_page(self):
        initial_page = InitialPage(self.driver)
        initial_page.validate_title()
        initial_page.validate_url()
        initial_page.validate_inputs()
        initial_page.validate_buttons()
        initial_page.click_login_button()
        #initial_page.click_signup_button()

    def test_login_page(self, cmd_opt_username, cmd_opt_password, cmd_opt_username_email):
        login_page_title = "Login on Twitter / Twitter"
        login_page = LoginPage(self.driver)
        login_page.validate_title(login_page_title)
        login_page.validate_url("https://twitter.com/login")
        login_page.validate_inputs()
        login_page.validate_links()
        login_page.validate_button()
        login_page.login(username=cmd_opt_username_email, password=cmd_opt_password)
        string_title = self.driver.instance.title
        if string_title == login_page_title:
            with allure.step("Repeat login by autogenerated username"):
                login_page = LoginPage(self.driver)
                login_page.login(username=cmd_opt_username, password=cmd_opt_password)

    def test_main_page(self):
        main_page = MainPage(self.driver)
        main_page.validate_url("https://twitter.com/home")
        main_page.validate_buttons()
        utc_now = datetime.utcnow()
        main_page.create_new_tweet(string_tweet="test: {}".format(str(utc_now)))
